RemoteDignostic/urls.py
from django.contrib import admin
from django.urls import include, path, re_path

from django.conf import settings
from django.conf.urls.static import static

from websocket import views



# @accept_websocket
# def echo(request):
#     if request.is_websocket:
#         lock = threading.RLock()
#         try:
#             lock.acquire()
#             clients.append(request.websocket)
#             print(1111111)
#             for message in request.websocket:
#                 if not message:
#                     break
#             #     for client in clients:
#             #         client.send(message)
#         finally:
#             clients.remove(request.websocket)
#             lock.release()


urlpatterns = [
    # re_path(r'^echo$', echo),
    path('chat/', include('websocket.urls')),
    path('admin/', admin.site.urls),
    re_path('media/img/[0-9A-F]{12}$', views.show_files),
    re_path('media/upload/[0-9A-F]{12}$', views.show_files),
]

urlpatterns \
    += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

websocket/urls.py
from django.urls import path, re_path

from . import views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # path('', views.index, name='index'),
    path('console', views.console, name='console'),
    # re_path('remote', views.remote_diagnostic, name='remote'),
    re_path('connect', views.ws_connect),
    re_path('client_upload/?.*', views.upload_from_client),
    re_path('upload', views.upload),
    re_path('show', views.showable),
    re_path('echo/?.*', views.echo),
    re_path('download', views.downloadable),
    re_path('macs', views.macs),
    re_path('client_mac', views.client_mac),
    re_path('test', views.test),
]

# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

websocket/models.py
from django.db import models


# Create your models here.
class MacModel(models.Model):
    mac_addr = models.CharField(max_length=20)


class UploadedClients(models.Model):
    client_macs = models.CharField(max_length=20)
    files = models.CharField(max_length=255, default="")


class IMG(models.Model):
    img = models.ImageField(upload_to='img')


class UploadModel(models.Model):
    upload_file = models.FileField(upload_to='upload')

    @property
    def file_url(self):
        if self.upload_file and hasattr(self.upload_file, 'url'):
            return self.upload_file.url

websocket/forms.py
from django import forms


class RemoteForm(forms.Form):
    command = forms.CharField(widget=forms.Textarea)


class MacForm(forms.Form):
    queue = forms.CharField(label='Mac address', max_length=100)


class LogForm(forms.Form):
    log = forms.CharField()


class ConsoleForm(forms.Form):
    command = forms.CharField(widget=forms.Textarea)

websocket/views.py
from django.shortcuts import render

# Create your views here.
from django.http import HttpResponse, StreamingHttpResponse
from django.core import serializers
from django.core.files.storage import default_storage
from django.core.files.base import ContentFile


from django.views.decorators.csrf import csrf_exempt

from .models import IMG, UploadModel, MacModel, UploadedClients
from django.conf import settings


from dwebsocket import require_websocket, accept_websocket
import threading

import os
import json
import time

from apscheduler.schedulers.background import BackgroundScheduler
from django_apscheduler.jobstores import DjangoJobStore, register_events, register_job

from collections import defaultdict


# struct:
# key : value
# mac : request.websocket
ws_dict = {}
web_ws_dict = {}

# struct:
# key : value
# mac : [message list]
tv_ws_message = defaultdict(list)

# struct:
# mac : true[log on]/false[log off]
ws_log_on = {}

roll_log = False

try:
    # 实例化调度器
    scheduler = BackgroundScheduler()
    # 调度器使用DjangoJobStore()
    scheduler.add_jobstore(DjangoJobStore(), "default")
    # 设置定时任务，选择方式为interval，时间间隔为1s
    # 另一种方式为每天固定时间执行任务，对应代码为：
    # @register_job(scheduler, 'cron', day_of_week='mon-fri', hour='9', minute='30', second='10',id='task_time')
    @register_job(scheduler,"interval", seconds=1)
    def dispatch_message():
        global web_ws_dict
        global roll_log

        try:
            if not web_ws_dict:
                return
            else:
                for mac in web_ws_dict.keys():
                    # msg_len = len(tv_ws_message[mac])
                    # if msg_len > 2:
                        # # print("dispatch_message mac: " + key)
                        # for msg in tv_ws_message[key].pop(0).split(b'\n'):
                        #     if msg is not b'':
                        #         web_ws_dict[key].send(msg)
                    if roll_log:
                        web_ws_dict[mac].send("FunLogEnd")
                        roll_log = False
        except:
            pass


    @register_job(scheduler, "interval", seconds=10000)
    def manager_clients_info():
        macs = MacModel.objects.all()
        for mac in macs:
            if mac.mac_addr in ws_dict.keys():
                print(mac.mac_addr)
            else:
                pass
                # MacModel.objects.filter(mac_addr=mac.mac_addr).delete()


    register_events(scheduler)
    scheduler.start()
except Exception as e:
    print(e)
    scheduler.shutdown()


def index(request):
    return render(request, 'diagnostic.html', {})


def list_to_str(a_list):
    return "\n".join(list(map(str, a_list)))


@csrf_exempt
def console(request):
    if request.method == 'POST':
        message = request.POST.__getitem__('value')

        mac = get_macaddr(request.get_full_path().encode(encoding="utf-8"))
        if mac is not None:
            try:
                if message == "Log_save_on":
                    ws_log_on[mac] = True
                else:
                    ws_dict[mac].send(message)

                ### sav log & command
                command_path = os.path.join("log", mac, time.strftime("command_%Y%m%d.txt", time.localtime()))
                if not default_storage.exists(command_path):
                    default_storage.save(command_path, ContentFile(""))
                    UploadedClients(files=command_path, client_macs=mac).save()

                fs_cmd = default_storage.open(command_path, mode="ab")
                fs_cmd.write(message.encode()+b'\n')
                fs_cmd.close()

                try:
                    if len(ws_log_on):
                        if ws_log_on[mac] is True:
                            log_path = os.path.join("log", mac, time.strftime("log_%Y%m%d.txt", time.localtime()))
                            if not default_storage.exists(log_path):
                                default_storage.save(log_path, ContentFile(""))
                                UploadedClients(files=log_path, client_macs=mac).save()

                            if len(tv_ws_message[mac]) > 0:
                                fs_log = default_storage.open(log_path, mode="ab")
                                fs_log.write(list_to_str(tv_ws_message[mac]).encode())
                                fs_log.close()
                finally:
                    tv_ws_message[mac].clear()
            except Exception as e:
                print(e)

    return render(request, 'console.html', {})

#
# def remote_diagnostic(request):
#     if request.method == 'POST':
#         form = RemoteForm(request.POST)
#         if form.is_valid():
#             for client in clients:
#                 message = form.cleaned_data['command']
#                 client.send(message)
#         else:
#             return HttpResponse("error")
#
#     return render(request, 'remote_diagnostic.html', {})


@require_websocket
def test(request):
    try:
        for message in request.websocket:
            request.websocket.send(message)
    finally:
        pass


def get_macaddr(line):
    if line.startswith(b'Macaddr:'):
        line = line.decode()
        mac = ":".join(line.split(":")[1:])
    elif line.find(b"macaddr") != -1:
        line = line.decode()
        mac_start_pos = line.index("macaddr=") + 8
        mac = line[mac_start_pos:mac_start_pos+12]
    else:
        line = line.decode()
        mac = "".join(line.split("/")[3:])
    return mac


def if_mac_exists(mac):
    global ws_dict
    if not ws_dict:
        return False
    else:
        try:
            if ws_dict[mac]:
                return True
        except:
            print("error if_mac_exists " + mac)
    return False


@require_websocket
def ws_connect(request):
    global ws_dict

    if request.websocket.is_closed():
        print("ws is closed!")
    # lock = threading.RLock()
    try:
        # lock.acquire()
        for message in request.websocket:
            if not message:
                for key in list(ws_dict.keys()):
                    if ws_dict[key] == request.websocket:
                        if request.websocket.is_closed():
                            del ws_dict[key]
                            if key in list(ws_log_on.keys()):
                                del ws_log_on[key]

            else:
                if message.startswith(b'Macaddr:'):
                    mac = get_macaddr(message)
                    # format mac from xx:xx:xx:xx:xx to xxxxxxxxxx
                    mac_format = mac.replace(":", "")
                    if not if_mac_exists(mac_format):
                        if not MacModel.objects.filter(mac_addr=mac).exists():
                            # save the mac
                            # save mac as xx:xx:xx:xx:xx
                            MacModel(mac_addr=mac).save()
                    # update ws_dict[mac]

                    ws_dict[mac_format] = request.websocket
                    # clients.append(request.websocket)
                else:
                    # if local_client is not None:
                    #     for msg in message.split(b'\n'):
                    #         if msg is not b'':
                    #             local_client.send(msg)
                    # print("append_message: " + str(message))
                    append_message(request.websocket, message)

                # for client in clients:
                #     if client.is_closed():
                #         print("closed client")
                #         clients.remove(client)
                #         for key in ws_dict.keys():
                #             if ws_dict[key] is client:
                #                 print(key)
                #                 macdb = MacModel.objects.get(mac_addr=key)
                #                 print(macdb)
                                # macdb.delete()

    finally:
        pass
    #     clients.remove(request.websocket)
    #     lock.release()


@require_websocket
def echo(request):
    global web_ws_dict
    if request.is_websocket:
        lock = threading.RLock()
        try:
            lock.acquire()

            mac = get_macaddr(request.get_full_path().encode(encoding="utf-8"))
            if mac is not None:
                web_ws_dict[mac] = request.websocket

            for message in request.websocket:
                if not message:
                    if request.websocket.is_closed():
                        print(request.get_full_path())
                        print("local ws closed!!")

                    # for client in locals_clients:
                    #     client.send(message)
        finally:
            # clients.remove(request.websocket)
            lock.release()


def save_file(file_obj, mac, type):
    sub_folder = 'upload'
    if type == "img":
        file_name = file_obj.img.name
        file = file_obj.img.file
        sub_folder = 'img'
        # img = Image.open(file)
        # img.save(file_path)
    else:
        file_name = file_obj.upload_file.name
        file = file_obj.upload_file.file

    file_path = os.path.join(sub_folder, mac, file_name)
    default_storage.save(file_path, ContentFile(file.read()))

    # if not UploadedClients.objects.filter(client_macs=mac).exists():
    #     UploadedClients(client_macs=mac).save()
    UploadedClients(files=file_path, client_macs=mac).save()


@csrf_exempt
def showable(request):
    client_macs = UploadedClients.objects.filter().values("client_macs").distinct()
    content = {
        'client_macs': client_macs,
    }
    return render(request, 'show.html', content)


@csrf_exempt
def downloadable(request):
    client_macs = UploadedClients.objects.filter().values("client_macs").distinct()

    content = {
        'client_macs': client_macs,
    }
    return render(request, 'download.html', content)


@csrf_exempt
def show_files(request):
    mac = request.get_full_path().split("/")[-1]
    files = UploadedClients.objects.filter(client_macs=mac)

websocket/templates/base.html
<!DOCTYPE html>
<html lang="zh-cn">
<head>
<meta charset="gb2312" />

    <title>{% block title %}default title{% endblock %}</title>
</head>

<div id="header">
	<h1>{% block h1 %}default head1{% endblock %}  </h1>
</div>


<body>
	<div id="content">
	{% block content %}
	{% endblock %}
	</div>
</body>
</html>

websocket/templates/download.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h2>Directory listing for upload/</h2>
<hr>
<ul>

{#{% for img in imgs %}#}
{#<img src='{{ img.img.url }}' />#}
{#{% endfor %}#}

{#    {% if files.upload_file %}#}
{#        {% for file in files %}#}
{#            <li><a href='{{ file.upload_file.url }}'>'{{ file.upload_file.url }}'</a>#}
{#        {% endfor %}#}
{#    {% endif %}#}


    {% for mac in client_macs %}
        <li><a href='/media/upload/{{ mac.client_macs }}'>'{{ mac.client_macs }}'</a>
    {% endfor %}


{#        {% for file in files %}#}
{#            <li><a href='{{ file.file_url|default_if_none:'#' }}'>'{{ file.file_url|default_if_none:'#' }}'</a>#}
{#        {% endfor %}#}
</ul>
<hr>
</body>
</html>

websocket/templates/remote_diagnostic.html
{% extends "base.html" %} 

{% block title %}Welcome to remote diagnostic page! {% endblock %}

{% block h1 %}远程诊断{% endblock %}
{% block content %}
{% load staticfiles %}

<script src="{% static '/js/jquery-3.3.1.min.js' %}"></script>
<script>
let socket = null;
let logBox = null;
let addressBox = null;


function addToLog(log) {
    logBox.value += log + '\n'
}

function connect() {
    let scheme = window.location.protocol == 'https:' ? 'wss://' : 'ws://';
    let defaultAddress = scheme + window.location.host + '/chat/echo';
    let url = defaultAddress;
    let protocols = 0;

  if ('WebSocket' in window) {
    if (protocols) {
      socket = new WebSocket(url, protocols);
    } else {
      socket = new WebSocket(url);
    }
  } else {
   return;
  }

  socket.onopen = function () {
    let extraInfo = [];
    if (('protocol' in socket) && socket.protocol) {
      extraInfo.push('protocol = ' + socket.protocol);
    }
    if (('extensions' in socket) && socket.extensions) {
      extraInfo.push('extensions = ' + socket.extensions);
    }

    let logMessage = 'Opened';
    if (extraInfo.length > 0) {
      logMessage += ' (' + extraInfo.join(', ') + ')';
    }
    addToLog(logMessage);
  };
  socket.onmessage = function (event) {
    if (('ArrayBuffer' in window) && (event.data instanceof ArrayBuffer)) {
      addToLog('< Received an ArrayBuffer of ' + event.data.byteLength +
               ' bytes')
    } else if (('Blob' in window) && (event.data instanceof Blob)) {
      addToLog('< Received a Blob of ' + event.data.size + ' bytes')
    } else {
      addToLog('< ' + event.data);
    }
  };
  socket.onerror = function () {
    addToLog('Error');
  };
  socket.onclose = function (event) {
    let logMessage = 'Closed (';
    if ((arguments.length == 1) && ('CloseEvent' in window) &&
        (event instanceof CloseEvent)) {
      logMessage += 'wasClean = ' + event.wasClean;
      // code and reason are present only for
      // draft-ietf-hybi-thewebsocketprotocol-06 and later
      if ('code' in event) {
        logMessage += ', code = ' + event.code;
      }
      if ('reason' in event) {
        logMessage += ', reason = ' + event.reason;
      }

    } else {
      logMessage += 'CloseEvent is not available';
    }
    addToLog(logMessage + ')');
  };

  if (protocols) {
    addToLog('Connect ' + url + ' (protocols = ' + protocols + ')');
  } else {
    addToLog('Connect ' + url);
  }
}

function init() {
    let scheme = window.location.protocol == 'https:' ? 'wss://' : 'ws://';
    let defaultAddress = scheme + window.location.host + '/chat/echo';


    logBox = document.getElementById('log');
    if (!('WebSocket' in window)) {
        addToLog(defaultAddress);
    }
    connect();
}

</script>
<link rel="stylesheet" type="text/css" href="{% static "ws/css/style.css" %}" />
<style type="text/css">
    .f-hidden {
        display: none;
    }
</style>
{{ query }}
<body id="editor" onload="init()">

    <iframe id="targetFrame" name="targetFrame" class="f-hidden"></iframe>
    <form id="post-form" action="/chat/remote/" method="post" target="targetFrame">
        {% csrf_token %}
        <script>
            // AJAX for posting
            function create_post() {
                console.log("create post is working!") // CH check
                {#console.log($('#id_command').val())#}
                $.ajax({
                    url : "/chat/remote/", // the endpoint
                    type : "POST", // http method
                    data : { the_post : $('#id_command').val() }, // data sent with the post request

                    // handle a successful response
                    success : function(json) {
                        $('#id_command').val(''); // remove the value from the input
                        console.log(json); // log the returned json to the console
                        console.log("success"); // another sanity check
                    },

                    // handle a non-successful response
                    error : function(xhr,errmsg,err) {
                        $('#results').html("<div class='alert-box alert radius' data-alert>Oops! We have encountered an error: "+errmsg+
                            " <a href='#' class='close'>&times;</a></div>"); // add the error to the dom
                        console.log(xhr.status + ": " + xhr.responseText); // provide a bit more info about the error to the console
                    }
                });
            };

            {#$('#post-form').on('submit', function(event){#}
            {#    event.preventDefault();#}
            {#    console.log("form submitted!")  // CH check#}
            {#    create_post();#}
            {#    return false#}
            {#});#}
        </script>
        {{ command }}
        <div id="butt">
            <input type="submit" name="sendContent" value="发送" >
        </div>

        <div id="CodeArea">
            <h2>输入命令：</h2>
            <textarea id="id_command" wrap="logical" name="command"></textarea>
        </div>
    </form>


	<div id="result">
		<h2>查看结果:</h2>
{#		<form action="rev" method="get">#}
		<textarea id="log" wrap="logical" readonly></textarea>
{#        </form>#}
	</div>

	<div id="footer">
		<p>请在上面的文本框中输入命令，然后单击发送。<a href="/index.html" title="default title">localhost:8000</a></p>
	</div>

</body>
{% endblock %}

websocket/templates/show.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h2>Directory listing for macs/</h2>
<hr>
<ul>



    {% for mac in client_macs %}
        <li><a href='/media/img/{{ mac.client_macs }}'>'{{ mac.client_macs }}'</a>
    {% endfor %}

{#    {% for img in imgs %}#}
{#        <li><a href='{{ img.img.url }}'>'{{ img.img.url }}'</a>#}
{#    {% endfor %}#}

</ul>
<hr>
</body>
</html>

websocket/templates/show_files.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h2>listing for files/</h2>
<hr>
<ul>

{#    {% for img in imgs %}#}
{#        <li><a href='{{ img.img.url }}'>'{{ img.img.url }}'</a>#}
{#    {% endfor %}#}

    {% for file in files %}
        <li><a href='/media/{{ file.files }}'>'{{ file.files }}'</a>
    {% endfor %}


</ul>
<hr>
</body>
</html>

websocket/templates/upload.html
<!DOCTYPE html>
{% load staticfiles %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

{#<form method="POST" enctype="multipart/form-data">#}
{#{% csrf_token %}#}
{#<input type="file" name="img">#}
{#<button type="submit">上传</button>#}
{#</form>#}


{# <form method="post" enctype="multipart/form-data">#}
{#      Enter file: <input type="file" name="img" size="40">#}
{#      Enter file name: <input type="text" name="filename" size="30">#}
{#      <input type="submit" value="send" name="submit">#}
{# </form>#}

{#<script src="{% static '/js/jquery-3.3.1.min.js' %}"></script>#}
{#<script>#}
{#    function uploadFile() {#}
{#        document.getElementById('iframe1').onload = reloadIframe1;#}
{#        document.getElementById('fm1').submit();#}
{#    }#}
{#    function reloadIframe1() {#}
{#        var content = this.contentWindow.document.body.innerHTML;#}
{#        var obj = JSON.parse(content);#}
{#        console.log(obj.data);    //obj.data 获取后端图片的路径#}
{#        var tag=document.createElement("img");#}
{#        tag.src=obj.data;#}
{#        $("#preview").empty().append(tag)  //先清空内容在添加#}
{#    }#}
{##}
{#</script>#}
</body>
</html>